apiVersion: scaffolder.backstage.io/v1beta3 
kind: Template
metadata:
  name: demo-one-of
  title:  Bug in One Of
  description: Bug Demo 
  tags: ["bug"]
spec:
  type: service 
  parameters: 
    - title: Choose One Of
      required:
        - hostType  
      properties:
        hostType:
          title: Host Type
          type: string
          enum:
            - GitHub
            - GitLab
            - Bitbucket
          default: GitHub 
      dependencies:
        hostType:
          oneOf:
            - required:
                - ghHost
                - commonHost 
              properties:
                hostType:
                  const: GitHub    
                ghHost:
                  title: ghHost
                  type: string
                  default: github.com
                commonHost:
                  title: commonHost
                  type: string
                  default: github.com
                  ui:help: "The default value should be github.com in both ghHost and commonHost"
            - required:
                - glHost
                - commonHost  
              properties:
                hostType:
                    const: GitLab   
                glHost:
                  title: glHost
                  type: string
                  default: gitlab.com
                commonHost:
                  title: commonHost
                  type: string
                  default: gitlab.com     
                  ui:help: "The default value should be gitlab.com in both glHost and commonHost"
            - required:
                - bbHost
                - commonHost  
              properties:
                hostType:
                    const: Bitbucket   
                bbHost:
                  title: bbHost
                  type: string
                  default: bitbucket.org  
                commonHost:
                  title: commonHost
                  type: string
                  default: bitbucket.org        
                  ui:help: "The default value should be bitbucket.org in both bbHost and commonHost" 
  steps:
    - id: demo-wait-
      name: Waiting for demo
      action: 'debug:wait'
      input:
        seconds: 3 
  output:
    links:
      - title: ThisRepoWithBugDemo
        url: https://github.com/jduimovich/oneof
         
